### ISSUE TITLE
Use smartfritz-promise?

### ISSUE THREAD

**Issue by andig** [bashGroup/node-red-contrib-smartfritz#2]
Would there be any using in utilizing https://www.npmjs.com/package/smartfritz-promise as basis? Should provide better functionality and abstraction than the original smartfritz library and might be usable without duplicating code?

**Comment by P1Rebo** [comment]
Hi andig, thanks for your input. I just updated the dependencies. Now using smartfritz-promise.

**Comment by andig** [comment]
I've just noticed that the dependencies have not been updated- only the readme...
