### ISSUE TITLE
node-red crashes when smartfritz is used

### ISSUE THREAD

**Issue by simonschllng** [bashGroup/node-red-contrib-smartfritz#7]
I can not use this package at all. Each time I trigger the nodes my node-red crashes. Is somebody else experiencing this?

**Comment by simonschllng** [comment]
Ok, found the problem and fixed it locally. But how to contribute? Is the maintainer still reading this? Why are there so many unmerged branches in forks?

**Comment by wernersv** [comment]
Maybe the maintainer is not working on this anymore. In this case you can create a fork to share your changes.

**Comment by simonschllng** [comment]
There is a more active branch here: https://github.com/mpolitze/node-red-contrib-smartfritz/tree/fixed
already asked @mpolitze if they want to maintain a public package. If not I will merge theirs and mine.
